### ISSUE TITLE
ROIs displayed tiny

### ISSUE THREAD

**Issue by eepeacock** [LouisK130/IFCB-Annotate#44]
![rois in annotate showing up tiny](https://user-images.githubusercontent.com/14059636/43530079-b16ed29a-957a-11e8-9810-775308ec3640.PNG)

So, this just happened.  Some or the ROIs showed up super tiny. I had not seen that before.

**Comment by LouisK130** [comment]
That is very strange. Is the problem reproducible? What settings / bins are you using?

**Comment by eepeacock** [comment]
I think not reproducible. I was working in batch mode on the category flagellate for either 2008 or 2009. I will repost if it happens again.

**Comment by LouisK130** [comment]
If you can identify the roi(s) for which this occurred, that would be helpful.
