### ISSUE TITLE
slow to or unable to load images

### ISSUE THREAD

**Issue by eepeacock** [LouisK130/IFCB-Annotate#46]
The load speed of images is variable. When we first started with the new tool last summer, it seemed like it was always faster than the matlab version. This is no longer the case. I know Gedeon has had slower and faster times - I have not had much time for annotations recently. But sometimes you just get white boxes:
![rois in annotation not appearing](https://user-images.githubusercontent.com/14059636/43531502-e92717c6-957d-11e8-8066-ae9d4d7d5848.PNG)

In this case, they did load in the amount of time it took me to write this issue.... 

Joe will say the NAS is too slow. Is the NAS really this variable?

**Comment by LouisK130** [comment]
I'm afraid this is more on Joe's end than mine. Your client is waiting for the Annotate server to give it the images, but the Annotate server is waiting to get them from the dashboard.

**Comment by joefutrelle** [comment]
This is batch mode, right?

**Comment by eepeacock** [comment]
It was, but I think it happens in either mode.

Quoting Joe Futrelle <notifications@github.com>:

**Comment by LouisK130** [comment]
In either mode you are likely viewing more than one bin. If some bins have been downloaded and others aren't done yet, you'll see some white images and some normal ones.

**Comment by eepeacock** [comment]
True, I rarely have in interest in viewing one bin at a time. One of  
the perks of the new system was the ability to view multiple bins. But  
sometimes, I wait and wait and a few white rectangles remain. I  
believe I reported this at the beginning, as well, but without  
frequent occurrence.




Quoting Louis Kilfoyle <notifications@github.com>:
