### ISSUE TITLE
Some class files won't/don't load in ifcb-annotate

### ISSUE THREAD

**Issue by eepeacock** [LouisK130/IFCB-Annotate#80]
I am using the tool, loading 2-3 MVCO files, and twice now, the last file in my list (2nd or 3rd) didn't get class results loaded. I try again with only that file loaded, and still no class results. The class files exist, and loaded into matlab they look the same as any other.

This just occurred with D20181120T205236_IFCB010_class_v1.mat.

Can anyone else replicate the problem?

All of the images show up in "other" and if I right click on them there is no line for auto - as if no class file existed.

**Comment by eepeacock** [comment]
Joe- would you have time to look at the logs and see why this file (D20181120T205236_IFCB010_class_v1.mat) does not load it's auto results? They are available via the dashboard, but do not show up in the annotation tool. Im 95% sure I have also seen this on other days, where some class files load and others do not. I will post if I get another example. I

**Comment by joefutrelle** [comment]
Unfortunately the logs are not informative on this issue. I read them all and didn't see any error related to this. If it happens again, please post the time at which it happened (in EST) so I can check the logs for errors around that time.

**Comment by eepeacock** [comment]
Well, if isn't occasional for this particular file, at least. I have  
not seen class results load for it yet. I used it this morning. What  
else can we do? All of the ROIs were in the default class, and right  
clicking on them revealed no class information. Can you try it on your  
computer and see if it is the same?




Quoting Joe Futrelle <notifications@github.com>:

**Comment by joefutrelle** [comment]
I can try it on my computer if you explain to me how to do it ...

**Comment by eepeacock** [comment]
Open the annotation tool, choose classify images, chose the MVCO  
timeseries, choose manual entry, add that file, check off "load  
autoclassifier results", don't choose anything in "views". Or we can  
do it when I see you. Are you working in lab today?


Quoting Joe Futrelle <notifications@github.com>:

**Comment by joefutrelle** [comment]
I think I fixed the problem. The issue was that the cached class scores JSON file was zero-length. I deleted that cached file, reattempted, and now I can see the auto class results. I'll open another issue about caching zero length files.

**Comment by eepeacock** [comment]
GREAT!

Quoting Joe Futrelle <notifications@github.com>:
