### ISSUE TITLE
ROIs with 2 tags are not displaying except when "ANY" is selected

### ISSUE THREAD

**Issue by eepeacock** [LouisK130/IFCB-Annotate#85]
The annotation tool stops on the combinaiton of a category with two tags for display purposes, but nothing is displayed, even tho ROIs do exist that should be displayed. If you switch the tag view to "ANY" then you see them. 
For example Bacillariophycaea with tags "empty frustule" and "external flagellate" on bin D20170530T193112_IFCB010.

**Comment by louis-kilfoyle** [comment]
Confirmed issue, thanks for the steps to reproduce. I'll try to look into it this weekend.

**Comment by LouisK130** [comment]
Sorry, I had forgotten about this.
