### ISSUE TITLE
Sort by: Autoclass highest score

### ISSUE THREAD

**Issue by eepeacock** [LouisK130/IFCB-Annotate#91]
In the main ifcb-annotate window where the images are shown, there is a drop down menu called "filter by:".

All of the choices prioritize some sort of manual annotation, if it exists, and show the auto-class result only if there is no manual annotation. We would like the option to prioritize auto-class score over any manual annotation. 

So, a choice in the filter by menu that says "Highest autoclass score"

**Comment by LouisK130** [comment]
Please see: https://github.com/LouisK130/IFCB-Annotate/issues/92#issuecomment-601981062

I think the behavior you want is achieved by adding a "sort" option, not a "filter" option.

**Comment by hsosik** [comment]
Joe - If you consider the "Select Views" page (which automatically appears right after "select bins"), can you see how to add a third radio button along the lines of "classifier only" as an additional option (instead of just "sort by user power" and "sort by annotation date")? This new option would display ROIs in the classes assigned by the imported autoclassifier scores (ignoring any user entries in the database).  Lou thinks this should relatively straightforward to add.

**Comment by LouisK130** [comment]
This will not work with custom views _at all_.

If you add custom views and select "prioritize classifier", the behavior here is undefined. I suspect you'll just get a 500 error.

**Comment by eepeacock** [comment]
Okay.

Do you expect "Filter by" to also not work? Or not work as it did when  
you started with "prioritize classifier"?

It doesn't give an error. I can understand how it would be more  
complicated for it to work as it did before if the classifier was  
given some power. Just want to confirm that it is not a bug.







Quoting Louis Kilfoyle <notifications@github.com>:

**Comment by eepeacock** [comment]
Sorry, I spoke too soon. "filter by" " Not annotated by anyone"  
appears to work once I have advanced to the next class and back again.  
That should be sufficient. They just don't hide immediately like they  
did before.


Quoting Louis Kilfoyle <notifications@github.com>:

**Comment by LouisK130** [comment]
You're right, "filter by" is broken in conjunction with "prioritize classifier". Should be fixable.

I don't think switching away and back is actually resolving anything, it's just broken in a different way. If you select "most powerful and most recent differ", it breaks the "prioritize classifier" part. Also fixable.

**Comment by eepeacock** [comment]
Thank you. I observed this indeed.




Quoting Louis Kilfoyle <notifications@github.com>:
